# SPDX-FileCopyrightText: 2024 Pablo Portas L贸pez <pablo.portas@udc.es>
#
# SPDX-License-Identifier: GPL-3.0-only

blank_issues_enabled: true
contact_links:
  - name:  隆Quiero a帽adir c贸digo!
    url: https://github.com/TeenBiscuits/Pro2324/pulls
    about: 隆Es genial oir eso! Para colaborar haznos una pull request.
  - name: 锔 Soporte
    url: https://github.com/TeenBiscuits/Pro2324/blob/main/CODEOWNERS
    about: Para cualquiera cuesti贸n o comunicaci贸n relacionada con este repositorio.
